# Generated by Django 4.2.7 on 2023-11-04 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comentario')),
                ('experiment_id', models.CharField(max_length=255, verbose_name='ID de Experimento')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_comparison_repeats', models.PositiveIntegerField(default=2)),
                ('multi_article_title_selection_repeats', models.PositiveIntegerField(default=2)),
                ('num_articles_shown', models.PositiveIntegerField(default=6)),
            ],
            options={
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100, null=True)),
                ('document_indices', models.TextField()),
                ('appearances', models.IntegerField()),
                ('occurrences', models.IntegerField()),
                ('synonyms', models.TextField()),
                ('n_synonyms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=200)),
                ('newspaper_name', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=100)),
                ('pompadour', models.TextField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('original_tags', models.TextField()),
                ('article_url', models.URLField()),
                ('newspaper_domain', models.URLField()),
                ('unique_id', models.IntegerField()),
                ('entities', models.ManyToManyField(to='newsbaitapp.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('session_id', models.CharField(max_length=100)),
                ('randomization_seed', models.IntegerField(default=0)),
                ('test_type', models.CharField(choices=[('title_comparison', 'Title Comparison'), ('multi_article_title_selection', 'Multi Article Title Selection')], max_length=50)),
                ('iteration_number', models.IntegerField(default=1)),
                ('options', models.TextField(default='[]')),
                ('selected_title', models.CharField(blank=True, max_length=500, null=True)),
                ('selected_section', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_position', models.PositiveIntegerField(blank=True, null=True)),
                ('selected_is_ai', models.BooleanField(default=False)),
                ('concordance_score', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('studies', models.CharField(blank=True, choices=[('secundario_incompleto', 'Secundario incompleto o menor'), ('secundario_completo', 'Secundario completo'), ('terciario_incompleto', 'Terciario o Universitario incompleto'), ('terciario_completo', 'Terciario o Universitario completo o superior')], max_length=100, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_article', to='newsbaitapp.news')),
                ('selected_tags', models.ManyToManyField(blank=True, related_name='selected_tags', to='newsbaitapp.entity')),
            ],
        ),
    ]
