# Generated by Django 4.2.7 on 2023-11-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsbaitapp', '0004_alter_experiment_studies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='configuration',
            name='min_appearances',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
