# Generated by Django 4.2.7 on 2023-11-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsbaitapp', '0005_delete_comment_configuration_min_appearances'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('input_token_count', models.IntegerField()),
                ('output_token_count', models.IntegerField()),
                ('input_spend', models.FloatField()),
                ('output_spend', models.FloatField()),
                ('total_spend', models.FloatField()),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('n_choices', models.IntegerField()),
                ('choices', models.JSONField(default=list)),
                ('model_resp', models.CharField(blank=True, max_length=50, null=True)),
                ('model_arg', models.CharField(max_length=50)),
                ('system_prompt', models.TextField()),
                ('input_prompt', models.TextField()),
                ('api_key_alias', models.SlugField()),
                ('extra_config', models.JSONField(default=dict)),
                ('testing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default='\nSoy el editor responsable de un medio digital. Quiero que, dado el texto de una noticia, los titulares de mi medio se generen de manera personalizada para cada usuario, de modo que capturen más su atención y lo inclinen a ver el contenido de la noticia. Para eso, tengo una lista de etiquetas para cada usuario, que representan sus temas o asuntos de interés. El procedimiento de optimización de títulos que pretendo de ChatGPT consiste en tomar las etiquetas del usuario, buscar en el texto si aparecen de manera explícita, similar o implícita, e intentar incluir esos temas en el titular, sin perder la consistencia interna del mismo ni la correspondencia con la noticia o texto en cuestión.\n\nTiene que seguir las líneas de estilo de un medio digital de noticias propio de Argentina. Sus respuestas deben ser titulares, en base al input entregado (1. texto de la noticia por un lado, 2. etiquetas del usuario por el otro). Los títulos de noticias deben cumplir las siguientes condiciones:\n- intentar incluir las etiquetas (o conceptos similares) de interés del usuario en base al contenido de la noticia.\n- mantener la congruencia interna del título.\n- mantener la correspondencia del título con el contenido de la noticia.\n- respetar el límite de palabras: 10 palabras.\n\nDebe generar 1 Output para cada Input. No debe haber otros elementos en el mensaje más que el título generado.\n')),
                ('api_key_alias', models.CharField(default='dmtmtp', max_length=50)),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=200)),
                ('testing', models.BooleanField(default=False)),
                ('extra_config', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(default='a', unique=True)),
                ('key', models.CharField(default='abc', max_length=300)),
                ('input_tokens_count', models.IntegerField(default=0)),
                ('output_tokens_count', models.IntegerField(default=0)),
                ('input_spend', models.FloatField(default=0)),
                ('output_spend', models.FloatField(default=0)),
                ('total_spend', models.FloatField(default=0)),
            ],
        ),
    ]
