# Generated by Django 4.2.7 on 2023-11-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsbaitapp', '0006_aicall_aiconfiguration_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
